# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
controllers:
  knbn:
    replicas: 1
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    containers:
      knbn:
        image:
          repository: jacob.pub/ghcr.io/kanbn/kan
          tag: 0.6.0@sha256:0087a72a123d8462c66ddce3a303049d4ec92f03cfba297d41466605ef8cb5b5
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 2000m
            memory: 5500Mi
          limits:
            cpu: 2000m
            memory: 10000Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
        env:
        - name: TZ
          value: America/Chicago

service:
  knbn:
    controller: knbn
    ports:
      http:
        port: 3000
