apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: public-extended-connect
  namespace: envoy-gateway-system
spec:
  type: JSONPatch
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: public
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: envoy-gateway-system/public/https
      operation:
        op: add
        path: /filter_chains/0/filters/0/typed_config/http2_protocol_options/allow_connect
        value: true
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: envoy-gateway-system/public/https-quic
      operation:
        op: add
        path: /filter_chains/0/filters/0/typed_config/http3_protocol_options/allow_extended_connect
        value: true
