apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trunk-recorder
  namespace: trunk-recorder
spec:
  interval: 1h
  targetNamespace: trunk-recorder
  path: ./apps/trunk-recorder/resources
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
