# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  dump978:
    replicas: 1
    containers:
      dump978:
        image:
          repository: jacob.pub/ghcr.io/sdr-enthusiasts/docker-dump978
          tag: telegraf-build-762
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - sh
                  - -c
                  - for n in /dev/bus/usb/*/*; do set -- $(stat -c '%t %T' "$n") && grep -qsx "$(printf '%d:%d' "0x$1" "0x$2")" /sys/bus/usb/devices/*/dev && ls -l /proc/[0-9]*/fd 2>/dev/null | grep -q " $n\$" || exit 1; done
              initialDelaySeconds: 60
              periodSeconds: 60
              timeoutSeconds: 10
              failureThreshold: 3
          readiness:
            enabled: true
          startup:
            enabled: true
        env:
          TZ: America/Chicago
          ENABLE_PROMETHEUS: "true"
          DUMP978_DEVICE_TYPE: rtlsdr
          DUMP978_SDR_GAIN: "15.7"
          DUMP978_RTLSDR_DEVICE: "00000978"
        envFrom:
          - secretRef:
              name: location
        resources:
          limits:
            memory: 224Mi
            squat.ai/rtl-sdr-uat: 1
          requests:
            cpu: 20m
            memory: 176Mi

service:
  dump978:
    controller: dump978
    ports:
      http:
        port: 80
        primary: true
      uat:
        port: 30978
      metrics:
        port: 9273

persistence:
  autogain:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn-ssd
    globalMounts:
      - path: /var/globe_history
        subPath: autogain

ingress:
  tailscale:
    enabled: true
    className: tailscale
    hosts:
      - host: dump978
        paths:
        - path: /
          pathType: Prefix
          service:
              identifier: dump978
              port: http
    tls:
      - hosts:
          - dump978

serviceMonitor:
  dump978:
    enabled: true
    serviceName: dump978
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        interval: 10s
        scrapeTimeout: 10s
