apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: terminal-pod-reaper
  namespace: terminal-pod-reaper
spec:
  interval: 1h
  install:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  releaseName: terminal-pod-reaper
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: '4.6.2'
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: chart-values
