apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-controller
  namespace: kube-system
spec:
  interval: 60m0s
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  dependsOn:
    - name: external-snapshotter-crds
  images:
    - name: registry.k8s.io/sig-storage/snapshot-controller
      newName: jacob.pub/registry.k8s.io/sig-storage/snapshot-controller
      newTag: v8.6.0
  patches:
    - target:
        kind: Deployment
        name: snapshot-controller
      patch: |
        - op: replace
          path: /spec/template/spec/containers/0/args/0
          value: --v=2
