---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dockers-private-runner-set
  namespace: actions-runners
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  releaseName: dockers-private-runner-set
  chart:
    spec:
      chart: gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        namespace: actions-runner-system
        name: actions-runner-controller
      version: 0.14.0
      interval: 1m0s
  install:
    remediation:
      retries: -1
  values:
    githubConfigSecret: github-app
    githubConfigUrl: "https://github.com/USA-RedDragon/dockers-private"
    maxRunners: 10
    template:
      spec:
        securityContext:
          fsGroup: 1001
        containers:
        - name: runner
          image: jacob.pub/ghcr.io/usa-reddragon/arc-runner:2.333.1@sha256:deb160c5bc391d0a6f14c0b02f78948dd46dc3ac117d8f34f29a6ee0236f5ca2
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOKS
              value: /home/runner/k8s-novolume/index.js
            - name: ACTIONS_RUNNER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACTIONS_RUNNER_IMAGE
              value: jacob.pub/ghcr.io/usa-reddragon/arc-runner:2.333.1@sha256:deb160c5bc391d0a6f14c0b02f78948dd46dc3ac117d8f34f29a6ee0236f5ca2
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
