---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustdar-runner-set
  namespace: actions-runners
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  releaseName: rustdar-runner-set
  chart:
    spec:
      chart: gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        namespace: actions-runner-system
        name: actions-runner-controller
      version: 0.14.0
      interval: 1m0s
  install:
    remediation:
      retries: -1
  values:
    githubConfigSecret: github-app
    githubConfigUrl: "https://github.com/USA-RedDragon/rustdar"
    maxRunners: 10
    template:
      spec:
        containers:
        - name: runner
          image: jacob.pub/ghcr.io/usa-reddragon/arc-runner:2.333.1@sha256:3200dd3cb16f446798fe1e207bf74fbc08d49a0db5044f9a81d9ffdeff9b11c2
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOKS
              value: /home/runner/k8s-novolume/index.js
            - name: ACTIONS_RUNNER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACTIONS_RUNNER_IMAGE
              value: jacob.pub/ghcr.io/usa-reddragon/arc-runner:2.333.1@sha256:3200dd3cb16f446798fe1e207bf74fbc08d49a0db5044f9a81d9ffdeff9b11c2
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
