---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: squallar-runner-set-lite
  namespace: actions-runners
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  releaseName: squallar-runner-set-lite
  chart:
    spec:
      chart: gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        namespace: actions-runner-system
        name: actions-runner-controller
      version: 0.14.2
      interval: 1m0s
  install:
    remediation:
      retries: -1
  values:
    githubConfigSecret: github-app-squallar
    githubConfigUrl: "https://github.com/Squallar"
    maxRunners: 10
    containerMode:
      type: kubernetes-novolume
    template:
      metadata:
        labels:
          policy.mcswain.dev/egress-kubeapi: "true"
      spec:
        securityContext:
          fsGroup: 1001
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                actions.github.com/scale-set-name: squallar-runner-set-lite
        containers:
        - name: runner
          image: jacob.pub/ghcr.io/usa-reddragon/arc-runner:2.337.0@sha256:c74c1ddae23439ac3eb38a5d16b9beb37fc7b98f2774982ae01428ecd8ac0b73
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
            - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
              value: /home/runner/hook-template/template.yaml
            - name: ACTIONS_RUNNER_PREPARE_JOB_TIMEOUT_SECONDS
              value: "1800"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 8Gi
          volumeMounts:
            - name: hook-template
              mountPath: /home/runner/hook-template
              readOnly: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
        volumes:
          - name: hook-template
            configMap:
              name: squallar-runner-lite-hook-template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squallar-runner-lite-hook-template
  namespace: actions-runners
data:
  template.yaml: |
    metadata:
      labels:
        actions.github.com/job-pod-of: squallar-runner-set-lite
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              actions.github.com/job-pod-of: squallar-runner-set-lite
      containers:
        - name: $job
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 8Gi
