apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: forward-auth
  namespace: navidrome
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: navidrome-navidrome-web
  oidc:
    provider:
      issuer: https://authentik.mcswain.dev/application/o/navidrome/
    clientIDRef:
      name: navidrome-oidc
    clientSecret:
      name: navidrome-oidc
    scopes: [openid, profile, offline_access]
    forwardAccessToken: true
    refreshToken: true
  jwt:
    providers:
      - name: authentik
        issuer: https://authentik.mcswain.dev/application/o/navidrome/
        remoteJWKS:
          uri: https://authentik.mcswain.dev/application/o/navidrome/jwks/
        claimToHeaders:
          - header: Remote-User
            claim: preferred_username
