# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  navidrome:
    replicas: 1

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

    containers:
      navidrome:
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        image:
          repository: jacob.pub/docker.io/deluan/navidrome
          tag: "0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2"
        resources: {}
        env:
          - name: TZ
            value: America/Chicago
          - name: ND_PROMETHEUS_ENABLED
            value: "true"
          - name: ND_PROMETHEUS_METRICSPATH
            value: "/metrics"
          - name: ND_ENABLEUSEREDITING
            value: "true"
          - name: ND_EXTAUTH_TRUSTEDSOURCES
            value: "172.17.0.0/16"
          - name: ND_EXTAUTH_USERHEADER
            value: "Remote-User"
          - name: ND_EXTAUTH_LOGOUTURL
            value: "https://authentik.mcswain.dev/application/o/navidrome/end-session/"
          - name: ND_LOGLEVEL
            value: "trace"
          - name: ND_ENABLEINSIGHTSCOLLECTOR
            value: "false"
          - name: ND_MUSICFOLDER
            value: /tmp/music
          - name: ND_CACHEFOLDER
            value: /cache
          - name: ND_BASEURL
            value: https://navidrome.mcswain.dev
          - name: ND_ENABLESHARING
            value: "true"
          - name: ND_DEFAULTSHAREEXPIRATION
            value: "168h" # 7 days
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

service:
  navidrome:
    controller: navidrome
    ports:
      http:
        port: 4533

serviceMonitor:
  navidrome:
    enabled: true
    serviceName: navidrome
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 10s
        scrapeTimeout: 10s

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
  cache:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
  music:
    enabled: true
    type: nfs
    path: /mnt/data/media/Music
    server: 192.168.1.135
    globalMounts:
      - readOnly: true
  tmp:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi
  tmp-music:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Mi
    globalMounts:
      - readOnly: true
        path: /tmp/music

route:
  navidrome-web:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - navidrome.mcswain.dev
    rules:
      - backendRefs:
          - name: navidrome
            port: 4533
        matches:
          - path:
              type: PathPrefix
              value: /
      - backendRefs:
          - name: navidrome
            port: 4533
        timeouts:
          request: 0s
          backendRequest: 0s
        matches:
          - path:
              type: PathPrefix
              value: /api/events

  navidrome-subsonic:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - navidrome.mcswain.dev
    rules:
      - backendRefs:
          - name: navidrome
            port: 4533
        matches:
          - path:
              type: PathPrefix
              value: /rest/
          - path:
              type: PathPrefix
              value: /share/
