# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  navidrome:
    replicas: 1

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

    containers:
      navidrome:
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        image:
          repository: jacob.pub/docker.io/deluan/navidrome
          tag: "0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2"
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        env:
          - name: TZ
            value: America/Chicago
          - name: ND_PROMETHEUS_ENABLED
            value: "true"
          - name: ND_PROMETHEUS_METRICSPATH
            value: "/metrics"
          - name: ND_ENABLEUSEREDITING
            value: "true"
          - name: ND_EXTAUTH_TRUSTEDSOURCES
            value: "172.17.0.0/16"
          - name: ND_EXTAUTH_USERHEADER
            value: "Remote-User"
          - name: ND_EXTAUTH_LOGOUTURL
            value: "https://authentik.mcswain.dev/application/o/navidrome/end-session/"
          - name: ND_LOGLEVEL
            value: "info"
          - name: ND_ENABLEINSIGHTSCOLLECTOR
            value: "false"
          - name: ND_MUSICFOLDER
            value: /tmp/music
          - name: ND_CACHEFOLDER
            value: /cache
          - name: ND_BASEURL
            value: https://navidrome.mcswain.dev
          - name: ND_ENABLESHARING
            value: "true"
          - name: ND_DEFAULTSHAREEXPIRATION
            value: "168h" # 7 days
          - name: ND_IMAGECACHESIZE
            value: "4096MB"
          - name: ND_SCANNER_SCHEDULE
            value: "24 * * * *"
          - name: ND_SCANNER_PURGEMISSING
            value: always
          - name: ND_TRANSCODINGCACHESIZE
            value: "4096MB"
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

  proxy:
    strategy: RollingUpdate
    replicas: 1
    pod:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    containers:
      navidrome-proxy:
        image:
          repository: jacob.pub/ghcr.io/usa-reddragon/navisteal
          tag: v0.0.9@sha256:226620ce3bca4ca9eb968e9c3efd92875e8d72f795c165feb74126d4685ecdae
          pullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
        env:
          - name: LOG_LEVEL
            value: debug
          - name: SUBSONIC
            value: http://navidrome:4533
          - name: METRICS_ENABLED
            value: "true"
          - name: METRICS_BIND
            value: "0.0.0.0"

service:
  navidrome:
    controller: navidrome
    ports:
      http:
        port: 4533
  proxy:
    controller: proxy
    ports:
      http:
        port: 8080
        primary: true
      metrics:
        port: 9000

serviceMonitor:
  navidrome:
    enabled: true
    serviceName: navidrome
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 10s
        scrapeTimeout: 10s
  proxy:
    enabled: true
    serviceName: proxy
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        interval: 10s
        scrapeTimeout: 10s

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    advancedMounts:
      navidrome:
        navidrome:
          - path: /data
  cache:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    advancedMounts:
      navidrome:
        navidrome:
          - path: /cache
  music:
    enabled: true
    type: nfs
    path: /mnt/data/media/Music
    server: 192.168.1.135
    advancedMounts:
      navidrome:
        navidrome:
          - path: /music
            readOnly: true
  tmp:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi
  tmp-music:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Mi
    advancedMounts:
      navidrome:
        navidrome:
          - path: /tmp/music
            readOnly: true

route:
  navidrome-web:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - navidrome.mcswain.dev
    rules:
      - backendRefs:
          - name: navidrome
            port: 4533
        matches:
          - path:
              type: PathPrefix
              value: /
      - backendRefs:
          - name: navidrome
            port: 4533
        timeouts:
          request: 0s
          backendRequest: 0s
        matches:
          - path:
              type: PathPrefix
              value: /api/events

  navidrome-sharing:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - navidrome.mcswain.dev
    rules:
      - backendRefs:
          - name: navidrome
            port: 4533
        matches:
          - path:
              type: PathPrefix
              value: /share/

  navidrome-subsonic:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - navidrome.mcswain.dev
    rules:
      - backendRefs:
          - name: navidrome-proxy
            port: 8080
        timeouts:
          request: 0s
          backendRequest: 0s
        matches:
          - path:
              type: PathPrefix
              value: /rest/
