apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: agent-pool-testing
spec:
  organization: test
  token:
    secretKeyRef:
      name: tfc-owner
      key: token
  name: agent-pool-testing
  agentTokens:
    - name: agent-pool-testing-token
  agentDeployment:
    replicas: 1
    spec:
      containers:
        - name: tfc-agent
          image: "jacob.pub/docker.io/hashicorp/tfc-agent:1.28.7@sha256:ce1582f8ae7de346dfc502abd88ba25de197b1703f4c049c97926057e54a980a"
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    cooldownPeriodSeconds: 30
