apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: agent-pool-testing
spec:
  organization: test
  token:
    secretKeyRef:
      name: tfc-owner
      key: token
  name: agent-pool-testing
  agentTokens:
    - name: agent-pool-testing-token
  agentDeployment:
    replicas: 1
    spec:
      containers:
        - name: tfc-agent
          image: "jacob.pub/docker.io/hashicorp/tfc-agent:1.28.8@sha256:a67d78ed7605eff91f9dd403f61bc45e3553a0893f5ef97f5f8103350e8bc882"
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    cooldownPeriodSeconds: 30
