apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: agent-pool-testing
spec:
  organization: test
  token:
    secretKeyRef:
      name: tfc-owner
      key: token
  name: agent-pool-testing
  agentTokens:
    - name: agent-pool-testing-token
  agentDeployment:
    replicas: 1
    spec:
      containers:
        - name: tfc-agent
          image: "jacob.pub/docker.io/hashicorp/tfc-agent:1.28.4@sha256:6e6a8476371b90e424626a8ab9cdb6858def000a59e277ccf3e122ba53bda9c0"
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    cooldownPeriodSeconds: 30
