apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: path-of-titans
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: restic
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/restic
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filebrowser
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/filebrowser
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rcon
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/rcon
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: a2s-exporter
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/a2s-exporter
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mtail
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/mtail
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rcon-exporter
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/rcon-exporter
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashboard
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: path-map
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/path-map
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obsidibot
  namespace: path-of-titans
spec:
  interval: 1h
  targetNamespace: path-of-titans
  path: ./apps/path-of-titans/resources/obsidibot
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
