apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: usa-reddragon
        namespace: flux-system
      version: '1.1.2'
      interval: 60m0s
  interval: 1h
  values:
    controllers:
      valkey:
        containers:
          valkey:
            image:
              repository: jacob.pub/docker.io/valkey/valkey
              tag: 8.1.6-alpine@sha256:cb3339abbd6e18942cd8ac3349f0c371a82ba5b6204b242563ba299e7956cbd0
            resources:
              limits:
                memory: 50Mi
              requests:
                memory: 30Mi
                cpu: 20m

    persistence:
      data:
        storageClass: longhorn-nvme
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
