apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: usa-reddragon
        namespace: flux-system
      version: '1.1.2'
      interval: 60m0s
  interval: 1h
  values:
    controllers:
      valkey:
        containers:
          valkey:
            image:
              repository: jacob.pub/docker.io/valkey/valkey
              tag: 9.1.0-alpine@sha256:a35428eba9043cc0b79dbe54100f0c92784f2de00ad09b01182bfb1c5c83d1bd
            resources:
              limits:
                memory: 50Mi
              requests:
                memory: 30Mi
                cpu: 20m

    persistence:
      data:
        storageClass: longhorn-nvme
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
