apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ultrafeeder
resources:
  - helm.yaml
configMapGenerator:
  - name: chart-values
    files:
      - values.yaml=values.yaml
  - name: telegraf-receiver
    files:
      - readsb_receiver_json.conf
    options:
      disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
