# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  dynatrace-otel-collector:
    replicas: 1
    containers:
      dynatrace-otel-collector:
        image:
          repository: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector
          tag: 0.53.0@sha256:05d73c5412afd8b5d4cafe9b803afdc9208bdee97feed1dd1d0abdf60ac44cc8
          pullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
service:
  dynatrace-otel-collector:
    controller: dynatrace-otel-collector
    ports:
      grpc:
        port: 4317

configMaps:
  config:
    data:
      config.yml: |
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
              http:
                endpoint: 0.0.0.0:4318

        exporters:
          debug:
            verbosity: detailed

        service:
          pipelines:
            traces:
              receivers: [otlp]
              processors: []
              exporters: [debug]
            metrics:
              receivers: [otlp]
              processors: []
              exporters: [debug]
            logs:
              receivers: [otlp]
              processors: []
              exporters: [debug]

persistence:
  configmap:
    enabled: true
    type: configMap
    name: dynatrace-otel-collector
    globalMounts:
    - path: /etc/otelcol/config.yaml
      subPath: config.yml
