# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  dynatrace-otel-collector:
    replicas: 1
    containers:
      dynatrace-otel-collector:
        image:
          repository: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector
          tag: 0.52.0@sha256:cd35098f75245b4d46da9ae2f6ee08f5d8191ae0a7b330c1888e83eb6a45c5e6
          pullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
service:
  dynatrace-otel-collector:
    controller: dynatrace-otel-collector
    ports:
      grpc:
        port: 4317

configMaps:
  config:
    data:
      config.yml: |
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
              http:
                endpoint: 0.0.0.0:4318

        exporters:
          otlp_http:
            endpoint: https://butts.lol

        service:
          pipelines:
            traces:
              receivers: [otlp]
              processors: []
              exporters: [otlp_http]
            metrics:
              receivers: [otlp]
              processors: []
              exporters: [otlp_http]
            logs:
              receivers: [otlp]
              processors: []
              exporters: [otlp_http]

persistence:
  configmap:
    enabled: true
    type: configMap
    name: dynatrace-otel-collector
    globalMounts:
    - path: /etc/otelcol/config.yaml
      subPath: config.yml
