apiVersion: v1
kind: Secret
metadata:
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
    name: github-api-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:prdORBC6J3QFSIo4WjQaxRjMiDmG7AXP0a8AXLsWIlZ4MOtDtchYRQ==,iv:w5pcG92E2jgqhZp4swrtrx3lWwQJK+8FF7d/FwAk9HA=,tag:iJllJMFdjGPpjHgnbsKDjg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-10-09T20:58:32Z"
    mac: ENC[AES256_GCM,data:LU7vkXAOvkWQ7O7axxBkGmpy/hchAXJ4xh9hmlPCZo7Uf6ZUMOLpUQaStGgnCxle4T2YP/WzL/SBlLkEo4J2idqxyPVRCReW9tGGSYnLVsMfwtRL+sYLX2lYorywxuW+DL7RPH/zQNVHKTkgMU/5Bf2bmdrfhGKzHAIuEJiWIiQ=,iv:h/89Xg61MHQaQhc/7rdHLbeI5h+UT5Iu53//VwrBV7A=,tag:iOsypA2iPgqeqk0e/DabNg==,type:str]
    pgp:
        - created_at: "2026-10-09T20:58:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4MMKSOyI68lAQ//cf4conhVI4qZmusYlT4PB96hsDodIFb7tzQ6Sz/KpZkV
            uC5Mzwm/hv3iBr//4QkbKhm0Hvm7sA+IO8PjfJysE5YgdUYF4Io5mqtqjahummGF
            EdP9ReovENjv72hieqi1bq2zZjMQZhPvQeIgAmWx3xDCmAO0bCQ5Tj9jmGqEopxE
            ZvtSHwib61xj1pWeRdB7yhHjYb7m2Ciouj0Yy+9gYzY/sh5i3FnbsPaLLbLoCrSN
            1aMNCIT0/t0q3tnFxPRGnVqHGcowP0GGDGCcSeFn0AXAGqj5RSQOuKP3cGkVr9jD
            zEoad3KdPZp3s9nrE6ZW4zCmWoT20yvmlPzl7M4yE+lMH6M9WB2tk3UtAZRLiyqj
            oma4vZ4fCfI6lxY6lu13bKM3ar71qUrjbOplDQ32tJwkvJZC9iKsd2ReM85fkF+j
            rUtDa5m3BixJuiC8YJ5UQ80+M4WLSwnbJ4VYuWnuVPCXHHYtoI0XdI5f3xwxkXtp
            wqf2hYL3paZVpmcCCCTMEVSVFKC6qixXffJTYzF5jfIQNMQ2oMHkSmezPhsqmf8A
            kmIDXN+e5vRh9GAwlcJ6HmKXd+plzN+MSqpFric8KQExkmm4O5wrbDH7yLAHBXoY
            C7MbtPVkR09Q21paIX4q119nbegvlOrBUMVAxQ0IODx905I/76Rpq1VeDAkPjLHS
            XgGGFLWoR2S3jQG+SJN2tMqT1lr4m58e1z8oDi44pBGrI4P7q+fh2FIbUQ5MVhM6
            1clHXBfYVGltZ3IO+G8W6LpfIXxsOtRIO2SR9L08m6/I7oC7vDAEbvHE001MhHI=
            =qFbC
            -----END PGP MESSAGE-----
          fp: A2BDE47C6914DA528CE96C6042D82D6196E0B4FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
