# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  cyberchef:
    replicas: 1
    containers:
      cyberchef:
        image:
          repository: jacob.pub/ghcr.io/gchq/cyberchef
          tag: 11.2.0@sha256:f829c2f358153b6b0ce5c226d97851e8728719d1e02e682bf7210d40663e93f9
          pullPolicy: IfNotPresent
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

service:
  cyberchef:
    controller: cyberchef
    ports:
      http:
        port: 8080

route:
  cyberchef:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - cyberchef.mcswain.dev
    rules:
      - backendRefs:
          - name: cyberchef
            port: 8080
        matches:
          - path:
              type: PathPrefix
              value: /
