# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  mqtt-wx:
    forceRename: mqtt-wx-app
    strategy: Recreate
    pod:
      enableServiceLinks: true
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    containers:
      app:
        image:
          repository: jacob.pub/ghcr.io/usa-reddragon/mqtt-wx
          tag: main@sha256:9d9dddbce44640b980d60a7d7a35e7ddbfef9dbdf01acbccd8fbfd5f9799644b
          pullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: passwords
        env:
        - name: INPUT_TOPIC_WEATHER
          value: rtl_433/Cotech-367959
        - name: INPUT_TOPIC_INDOOR
          value: weather-esphome/indoor-sensors
        - name: INPUT_TOPIC_LIGHTNING
          value: weather-esphome/lightning
        - name: INPUT_TOPIC_LIGHT
          value: weather-esphome/light
        - name: INPUT_TOPIC_PRESSURE
          value: weather-esphome/weather
        - name: INPUT_TOPIC_PARTICLE_SENSOR
          value: weather-esphome/particle-sensor
        - name: INPUT_TOPIC_CO2
          value: weather-esphome/living-room-scd40
        - name: OUTPUT_TOPIC
          value: weather/station
        - name: STATE_FILE
          value: /data/state.json
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 1m
            memory: 64Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
service:
  app:
    forceRename: mqtt-wx-app
    controller: mqtt-wx
    ports:
      http:
        port: 80
persistence:
  data:
    type: persistentVolumeClaim
    forceRename: data
    retain: true
    storageClass: longhorn-ssd
    accessMode: ReadWriteOnce
    size: 128Mi
    advancedMounts:
      mqtt-wx:
        app:
        - path: /data
          subPath: data
