# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  mqtt-wx:
    forceRename: mqtt-wx-app
    strategy: Recreate
    pod:
      enableServiceLinks: true
    containers:
      app:
        image:
          repository: jacob.pub/ghcr.io/usa-reddragon/mqtt-wx
          tag: main@sha256:5cf34d6d46ad71b3f05f3d35d5d25e5452e3d8cb4af6a6b5824a33e88a66182c
          pullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: passwords
        env:
        - name: INPUT_TOPIC_WEATHER
          value: rtl_433/Cotech-367959
        - name: INPUT_TOPIC_INDOOR
          value: weather-esphome/indoor-sensors
        - name: INPUT_TOPIC_LIGHTNING
          value: weather-esphome/lightning
        - name: INPUT_TOPIC_LIGHT
          value: weather-esphome/light
        - name: INPUT_TOPIC_PRESSURE
          value: weather-esphome/weather
        - name: INPUT_TOPIC_PARTICLE_SENSOR
          value: weather-esphome/particle-sensor
        - name: INPUT_TOPIC_CO2
          value: weather-esphome/living-room-scd40
        - name: OUTPUT_TOPIC
          value: weather/station
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 1m
            memory: 64Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
service:
  app:
    forceRename: mqtt-wx-app
    controller: mqtt-wx
    ports:
      http:
        port: 80
