---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-peer-relay
  namespace: tailscale-peer-relay
spec:
  install:
    remediation:
      retries: -1
  interval: 60m0s
  maxHistory: 2
  releaseName: tailscale-peer-relay
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chart-values
