controllers:
  mariadb:
    containers:
      mariadb:
        image:
          repository: jacob.pub/docker.io/mariadb
          tag: 12.1.2@sha256:f54db0cb3ccfe9431aba6d08c65a1763c499789b116b4cb651dd7fcf325965b3
        env:
          MARIADB_DATABASE: indi_allsky
          MARIADB_USER: indi_allsky
        resources:
          requests:
            memory: 256Mi
            cpu: 40m
          limits: {}

persistence:
  data:
    storageClass: longhorn-nvme
    accessMode: ReadWriteOnce
    size: 8Gi
