controllers:
  mariadb:
    containers:
      mariadb:
        image:
          repository: jacob.pub/docker.io/mariadb
          tag: 12.2.2@sha256:b3af559fc38e013c50dd5b5993bfbbb21125c1a62d976b3b0a14d9c4acaae578
        env:
          MARIADB_DATABASE: indi_allsky
          MARIADB_USER: indi_allsky
        resources:
          requests:
            memory: 256Mi
            cpu: 40m
          limits: {}

persistence:
  data:
    storageClass: longhorn-nvme
    accessMode: ReadWriteOnce
    size: 8Gi
