apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: immich
spec:
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/source: enabled
      recurring-job.longhorn.io/trim: enabled
  instances: 3
  imageName: jacob.pub/ghcr.io/tensorchord/cloudnative-vectorchord:18.6-1.1.1@sha256:c7672bc011351a587cc292a94aac7eeebb593ed2e120077bd9c9944c9467db93
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
  postgresql:
    shared_preload_libraries:
      - vchord.so
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg/immich"
      endpointURL: "https://s3.mcswain.dev"
      s3Credentials:
        accessKeyId:
          name: cnpg-minio
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-minio
          key: AWS_SECRET_ACCESS_KEY
      data:
        compression: lz4
      wal:
        compression: zstd
    retentionPolicy: "4w"
  storage:
    storageClass: longhorn-nvme-r1
    size: 12Gi
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: 450Mi
      cpu: 100m
  smartShutdownTimeout: 30
  stopDelay: 300
---
apiVersion: v1
kind: Secret
metadata:
 name: cnpg-minio
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: reflector/cnpg-minio
type: Opaque
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup
spec:
  immediate: true
  schedule: "0 5 * * * *"
  backupOwnerReference: self
  cluster:
    name: postgresql
