# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  redis:
    forceRename: redis-app
    strategy: Recreate
    pod:
      enableServiceLinks: true
    containers:
      app:
        image:
          repository: jacob.pub/docker.io/redis
          tag: 8.10.2-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0
          pullPolicy: IfNotPresent
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 6379
          readiness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 6379
service:
  app:
    forceRename: redis-app
    controller: redis
    ports:
      redis:
        port: 6379
