apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram-bot-token
    namespace: monitoring
stringData:
    telegram_bot_token: ENC[AES256_GCM,data:cZV+xeIyUxOqe574fSptopwx9zW+BowLzgYOc8gdE0frhmkauLP7PvLz04CzFA==,iv:BvMn9zLrRulcOh3tBAn/bofKRHgLpGScjVtP/o3hFII=,tag:DQ/VwWJ/DjbQVWHUbdDY2Q==,type:str]
    healthchecks_watchdog_url: ENC[AES256_GCM,data:yOE+BrcgWi95umCHzYTTG7mbHReRBgj10xzBmqKFf67jtcz6/rkUAuQ+3vUi77E1okwkSQ7J5h4=,iv:kwUjN+1/PhxiTtjHGcSE/7HM6PU7PZ3oN1KCdnKvWro=,tag:sCzptlYxHOkSmRxWwhHTmg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-10-09T06:19:43Z"
    mac: ENC[AES256_GCM,data:L1pUFKWLW6lfekkioK6ZowJ7kc5lUkFz9jmLA7kxNl7C3371VKSMzMuqLSLndKtrLMyCKy5/TmSW7as1gECRDny52A7LyJgQgnozqQLVk9cv8nrBn8qmG+1vZlEzc5Ncb3ZjGDS6adEtFsIjd02GDfK843PGUJH08sr7z3/0m9Q=,iv:7BIsHixI1tIVcobaRLCPvz2iwFFP5EfANJVqeFRV1p0=,tag:iv8JD8vh+17nm+L0uRrEUA==,type:str]
    pgp:
        - created_at: "2026-10-09T06:19:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4MMKSOyI68lARAAzlaOy290EBHzetc/C/GwrbTMXzV55msGObZTiZrlRbe2
            jVryFzBSOhZEUbLBR0hwQtVhKEU1H7MIeqyYeIp9xRN6inJCCMEbgNUJFRawuGIK
            PeX8xZT+cb0J4AKcr90umXjAuey8CL2tnUEIDjhX5GEmTc50KMEzliHo7jE8ZNLi
            ssGpkNa/BZjsjLqiZ/FS2wXiur6ye0dB3lBdGLglIX8A5pTLipcbgejH+BKM51Xn
            FmS4tWpNYE35gkSSWGQ14Qv3wF0FSx6PWuAANMxgmPzX6IHquF3C70BegcchWv/0
            rbmJ0FmTd/F0jTKYweTDSP39p1MWqR/+MusPJ3FJxyUzkvUSXvw2FCM9KUsEBVN6
            wTcDYzOuUisBA7h64wAKGHceJYqSQmZuBgG4939sYl0hjjUjyTvr1tbIKcGuRXlS
            o4w4q9UZ+nJWvhUBjnzRgBVLrKGzCHoFnkZgWdshveGFe7/NG1DhC17iolyJ9/vh
            MbxD8dazLwfQl85aU3+zHSYzOKo13nYXY+pxaLFY+v22tJ68XCt8fNgBoqHCQJ/2
            RYfpdKO/Y0yhOImhDaI2HJIN5SK5qtHt7LxxYF2evKH7acCDRFdGbiZuVG6zHoeq
            WmyUsZcTCs1Get+3mpRfm+AkChv6KH5c8HasaBdcNmQCjdm/hGvvpwWw17+WjI/S
            XgELBE20EWJW4pk9QvRUpHO13B+yPew4HSyENkQuEIYdinBTSFRx/ZI6Mpo/o4qd
            oIbjrYyJbQrJgOnCfz35wspg+NbnLB0dbi0Zny/WUD8/ogsVNKv9Ls3uC5FabeM=
            =qqwa
            -----END PGP MESSAGE-----
          fp: A2BDE47C6914DA528CE96C6042D82D6196E0B4FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
