# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  reticulum:
    replicas: 1

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

    containers:
      reticulum:
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        image:
          repository: jacob.pub/ghcr.io/usa-reddragon/reticulum
          tag: "1.2.0@sha256:9599266bdc15c8aa2d7bc499a4140bab1b42ab5b34831a3b992a203c599ae0a8"
        resources: {}
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

configMaps:
  config:
    data:
      config.toml: |
        [reticulum]
          enable_transport = true

        [interfaces]
          [[Server]]
            type = BackboneInterface
            enabled = true
            mode = gateway
            listen_on = 0.0.0.0
            port = 4242

            discoverable = true
            discovery_name = "Central Oklahoma Reticulum Hub"
            reachable_on = reticulum.mcswain.dev
            discovery_stamp_value = 30
            latitude = 35.324577
            longitude = -97.4594459
            height = 4

          [[RNode LoRa]]
            type = RNodeInterface
            enabled = true
            port = tcp://172.29.1.216
            frequency = 925875000
            bandwidth = 250000
            txpower = 22
            spreadingfactor = 9
            codingrate = 5
            flow_control = true

            discoverable = true
            discovery_name = "Central Oklahoma LoRa"
            discovery_stamp_value = 30
            latitude = 35.324577
            longitude = -97.4594459
            height = 4

          [[g00n.cloud Hub]]
            type = BackboneInterface
            enabled = true
            target_host = dfw.us.g00n.cloud
            target_port = 6969

service:
  reticulum:
    controller: reticulum
    ports:
      data:
        port: 4242

persistence:
  config:
    enabled: true
    type: configMap
    name: reticulum
    advancedMounts:
      reticulum:
        reticulum:
        - path: /app/.reticulum/config
          subPath: config.toml
  storage:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn-ssd
    advancedMounts:
      reticulum:
        reticulum:
          - path: /app/.reticulum/storage
  interfaces:
    enabled: true
    type: emptyDir
    sizeLimit: 1Gi
    advancedMounts:
      reticulum:
        reticulum:
          - path: /app/.reticulum/interfaces
  tmp:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi

route:
  data:
    enabled: true
    kind: TCPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: reticulum-data
    rules:
      - backendRefs:
          - name: reticulum
            port: 4242
