# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  rtl-433:
    forceRename: rtl-433-app
    strategy: Recreate
    pod:
      enableServiceLinks: true
      hostname: rtl-433
    containers:
      app:
        image:
          repository: jacob.pub/ghcr.io/hertzg/rtl_433_docker
          tag: 24.10-alpine@sha256:6330fb6523957a84d41aa1bda23e81132c65e8fff67dbdc98fbb31248168efe7
          pullPolicy: IfNotPresent
        args:
        - -c
        - /etc/rtl_433/service.conf
        - -R
        - '153'
        - -R
        - '20'
        - -R
        - '55'
        - -R
        - '73'
        - -M
        - level
        - -M
        - time
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec: &probe
                command:
                - sh
                - -c
                - for n in /dev/bus/usb/*/*; do set -- $(stat -c '%t %T' "$n") && grep -qsx "$(printf '%d:%d' "0x$1" "0x$2")" /sys/bus/usb/devices/*/dev && ls -l /proc/[0-9]*/fd 2>/dev/null | grep -q " $n\$" || exit 1; done
              periodSeconds: 60
              timeoutSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            custom: true
            spec:
              exec: *probe
              periodSeconds: 5
              timeoutSeconds: 10
              failureThreshold: 24
        env:
        - name: TZ
          value: America/Chicago
        resources:
          limits:
            memory: 30Mi
            squat.ai/rtl-sdr-433: 1
          requests:
            cpu: 3m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
service:
  app:
    forceRename: rtl-433-app
    controller: rtl-433
    ports:
      http:
        port: 80
persistence:
  config:
    type: secret
    name: config
    items:
    - key: service.conf
      path: service.conf
    advancedMounts:
      rtl-433:
        app:
        - path: /etc/rtl_433/
          readOnly: true
