loadBalancerClass: "metallb"

prometheus:
  podMonitor:
    enabled: true

  prometheusRule:
    enabled: true

  rbacPrometheus: false

controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.16.0@sha256:615b454c45e424e61d1f82c916ad7ab8c11ef2ba09d3ec4b0b64458e4058ff2b
  resources: {}
  # v0.16.0 ships with a hard-coded health check on 127.0.0.1, this isn't reachable from kubelet
  # so until they fix this, we need to disable the probes. https://github.com/metallb/metallb/pull/3062/changes
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.16.0@sha256:70e7f83255af2e96acfd574ac9f049745639deb2746d35e988008afcc0b80dbd
  resources: {}
  updateStrategy:
    type: OnDelete

  reloader:
    resources: {}

  frrMetrics:
    resources: {}

  extraContainers: []

frrk8s:
  enabled: false

crds:
  enabled: true
  validationFailurePolicy: Fail
