loadBalancerClass: "metallb"

prometheus:
  podMonitor:
    enabled: true

  prometheusRule:
    enabled: true

  rbacPrometheus: false

controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.16.1@sha256:f51ab515de9ccd20dc3dccb093e48df8adddac019326c456f449e55ba91b6420
  resources: {}
  # v0.16.0 ships with a hard-coded health check on 127.0.0.1, this isn't reachable from kubelet
  # so until they fix this, we need to disable the probes. https://github.com/metallb/metallb/pull/3062/changes
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.16.0@sha256:70e7f83255af2e96acfd574ac9f049745639deb2746d35e988008afcc0b80dbd
  resources: {}
  updateStrategy:
    type: OnDelete

  reloader:
    resources: {}

  frrMetrics:
    resources: {}

  extraContainers: []

frrk8s:
  enabled: false

crds:
  enabled: true
  validationFailurePolicy: Fail
