loadBalancerClass: "metallb"

prometheus:
  podMonitor:
    enabled: true

  prometheusRule:
    enabled: true

  rbacPrometheus: false

controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.15.3
  resources: {}

speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.15.3
  resources: {}
  updateStrategy:
    type: OnDelete
  frr:
    enabled: false
    image:
      repository: quay.io/frrouting/frr
      tag: 10.6.1@sha256:813497af103e972600f6161012b3bf2a2a1c5ea10d09cd1eacd74f1dc510a57b
    metricsPort: 7473
    resources: {}

  reloader:
    resources: {}

  frrMetrics:
    resources: {}

  extraContainers: []

crds:
  enabled: true
  validationFailurePolicy: Fail
