apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obico
  namespace: obico
spec:
  interval: 1h
  targetNamespace: obico
  path: ./apps/obico/resources/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: valkey
  namespace: obico
spec:
  interval: 1h
  targetNamespace: obico
  path: ./apps/obico/resources/valkey
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  commonMetadata:
    annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
