apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: usa-reddragon
        namespace: flux-system
      version: '1.1.2'
      interval: 60m0s
  interval: 1h
  values:
    controllers:
      valkey:
        containers:
          valkey:
            image:
              repository: jacob.pub/docker.io/valkey/valkey
              tag: 9.0.0-alpine@sha256:b4ee67d73e00393e712accc72cfd7003b87d0fcd63f0eba798b23251bfc9c394

    persistence:
      data:
        storageClass: longhorn-nvme-no-replicas
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
