---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcondev-oss
  namespace: actions-cache
spec:
  interval: 1m0s
  type: oci
  url: oci://ghcr.io/falcondev-oss/charts
