# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  rtl-433:
    forceRename: rtl-433-app
    strategy: Recreate
    pod:
      enableServiceLinks: true
    containers:
      app:
        image:
          repository: jacob.pub/ghcr.io/hertzg/rtl_433_docker
          tag: 24.10-alpine@sha256:9bed79a5c5848fe9af2d2f73acd6c925204102e12d2f05c774437e3df5e1f2e9
          pullPolicy: IfNotPresent
        args:
        - -c
        - /etc/rtl_433/service.conf
        - -R
        - '153'
        - -R
        - '20'
        - -R
        - '55'
        - -R
        - '73'
        - -M
        - level
        - -M
        - time
        env:
        - name: TZ
          value: America/Chicago
        resources:
          limits:
            memory: 30Mi
            squat.ai/rtl-sdr-433: 1
          requests:
            cpu: 3m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
service:
  app:
    forceRename: rtl-433-app
    controller: rtl-433
    ports:
      http:
        port: 80
persistence:
  config:
    type: secret
    name: config
    items:
    - key: service.conf
      path: service.conf
    advancedMounts:
      rtl-433:
        app:
        - path: /etc/rtl_433/
          readOnly: true
