apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rtz
  namespace: rtz
spec:
  interval: 1h
  targetNamespace: rtz
  path: ./apps/rtz/resources
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
