---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nats
  namespace: rtz
spec:
  interval: 1m0s
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: rtz
spec:
  install:
    remediation:
      retries: -1
  interval: 1m0s
  driftDetection:
    mode: enabled
  releaseName: nats
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
      version: '2.12.6'
      interval: 1m0s
  values:
    container:
      image:
        repository: jacob.pub/docker.io/nats
        tag: 2.12.8-alpine@sha256:6b2156f7491cdeddfa8b7ca15cd6fd59b9cabadec5019e933c65c01cf82b1c5f
      env:
        TOKEN:
          valueFrom:
            secretKeyRef:
              name: rtz
              key: nats-token
    reloader:
      enabled: false
    promExporter:
      enabled: true
      image:
        repository: jacob.pub/docker.io/natsio/prometheus-nats-exporter
        tag: 0.19.2@sha256:5387a5923572d154c9d609b3588397ca6b09b6004464cc4a80fc9e16c7b059b3
      podMonitor:
        enabled: true
    natsBox:
      enabled: false
    config:
      monitor:
        enabled: true
      cluster:
        enabled: true
      merge:
        authorization:
          token: << $TOKEN >>
        max_payload: << 32MB >>
