apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-crds
  namespace: kube-system
spec:
  interval: 1h
  targetNamespace: kube-system
  path: ./infrastructure/csi-snapshotter/resources/crds
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  commonMetadata:
    annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-controller
  namespace: kube-system
spec:
  interval: 1h
  targetNamespace: kube-system
  path: ./infrastructure/csi-snapshotter/resources/controller
  prune: true
  dependsOn:
    - name: csi-snapshotter-crds
      namespace: kube-system
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  commonMetadata:
    annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
