operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.96.5@sha256:7ea50edd505a7e5502f9f424e7d1670151ea97cc0e2d2b7c1772c53a158434a3
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.96.5@sha256:dbeff02d2337344b351afac203427218c4d0a06c43fc10a865184063498472a6

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
