operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.102.2@sha256:eaef921470ada74a84ca8bbbf4a6a89452ed2581d51a0551758507aca8dc2a01
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.102.2@sha256:321ce041508c19079b57a28b6666c8d81ab0b08accc0a2585b3ab663d557ac24

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
