apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale
spec:
  metrics:
    enable: true
  statefulSet:
    pod:
      nodeSelector:
        kubernetes.io/os: "linux"
      imagePullSecrets:
        - name: registry-zot
      tailscaleContainer:
        image: jacob.pub/ghcr.io/tailscale/tailscale:v1.102.5@sha256:c507f3a2a6ab1cabd8d809b98edeb41edbd5c3fb6ad9632ffd098b4c7d0b4065
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
          appArmorProfile:
            type: Unconfined
      tailscaleInitContainer:
        image: jacob.pub/ghcr.io/tailscale/tailscale:v1.102.5@sha256:c507f3a2a6ab1cabd8d809b98edeb41edbd5c3fb6ad9632ffd098b4c7d0b4065
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
          appArmorProfile:
            type: Unconfined
