apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale
spec:
  metrics:
    enable: true
  statefulSet:
    pod:
      nodeSelector:
        kubernetes.io/os: "linux"
      imagePullSecrets:
        - name: registry-zot
      tailscaleContainer:
        image: jacob.pub/ghcr.io/tailscale/tailscale:v1.98.10@sha256:cdf5612ded5be1344f1a704b8c5e53496db97376bb533e5e15f141e48bf60cc0
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
          appArmorProfile:
            type: Unconfined
      tailscaleInitContainer:
        image: jacob.pub/ghcr.io/tailscale/tailscale:v1.98.10@sha256:cdf5612ded5be1344f1a704b8c5e53496db97376bb533e5e15f141e48bf60cc0
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
          appArmorProfile:
            type: Unconfined
