apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale
spec:
  metrics:
    enable: true
  statefulSet:
    pod:
      nodeSelector:
        kubernetes.io/os: "linux"
      imagePullSecrets:
        - name: registry-zot
      tailscaleContainer:
        image: jacob.pub/ghcr.io/tailscale/tailscale:v1.98.9@sha256:f15d5d3f4a68773a853180b72496f70ba614b64de0878c43fe3da39fe0afba47
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
          appArmorProfile:
            type: Unconfined
      tailscaleInitContainer:
        image: jacob.pub/ghcr.io/tailscale/tailscale:v1.98.9@sha256:f15d5d3f4a68773a853180b72496f70ba614b64de0878c43fe3da39fe0afba47
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
          appArmorProfile:
            type: Unconfined
