replicaCount: 2

operator:
  image:
    repository: jacob.pub/docker.io/hashicorp/hcp-terraform-operator
    tag: "2.11.4@sha256:8aaae8bbe11f6e2c0726f59395880172e1d1f2d620e5563891ee08fef0ce550e"

  syncPeriod: 1h

  tfeAddress: "https://tfe.mcswain.dev"

  env:
    TF_LOG_OPERATOR: debug

kubeRbacProxy:
  image:
    repository: jacob.pub/quay.io/brancz/kube-rbac-proxy
    tag: v0.22.0@sha256:53d5a3911ac076d000c92362d4939a3147ba21f231edf82926c82d16dbdd8850

controllers:
  agentPool:
    workers: 1
    syncPeriod: 30s
  module:
    workers: 1
    syncPeriod: 5m
  project:
    workers: 1
    syncPeriod: 5m
  workspace:
    workers: 1
    syncPeriod: 5m
