replicaCount: 2

operator:
  image:
    repository: jacob.pub/docker.io/hashicorp/hcp-terraform-operator
    tag: "2.11.4@sha256:8aaae8bbe11f6e2c0726f59395880172e1d1f2d620e5563891ee08fef0ce550e"

  syncPeriod: 1h

  tfeAddress: "https://tfe.mcswain.dev"

  env:
    TF_LOG_OPERATOR: debug

kubeRbacProxy:
  image:
    repository: jacob.pub/quay.io/brancz/kube-rbac-proxy
    tag: v0.21.2@sha256:23bf4d4ddbb6827ede3a26d98814e3f3733b257e8b70de54c77e78eb7ed6d719

controllers:
  agentPool:
    workers: 1
    syncPeriod: 30s
  module:
    workers: 1
    syncPeriod: 5m
  project:
    workers: 1
    syncPeriod: 5m
  workspace:
    workers: 1
    syncPeriod: 5m
