replicaCount: 2

operator:
  image:
    repository: jacob.pub/docker.io/hashicorp/hcp-terraform-operator
    tag: "2.11.3@sha256:fb812a7ce1720bcdd88ae45658329a8141fedf4ff9477663782a9a1fb2c5beea"

  syncPeriod: 1h

  tfeAddress: "https://tfe.mcswain.dev"

  env:
    TF_LOG_OPERATOR: debug

kubeRbacProxy:
  image:
    repository: jacob.pub/quay.io/brancz/kube-rbac-proxy
    tag: v0.21.1@sha256:8ee55a15d8b066c8817f6fb7c0ac0e6238145d87c540a7271c32fbadab0b24e1

controllers:
  agentPool:
    workers: 1
    syncPeriod: 30s
  module:
    workers: 1
    syncPeriod: 5m
  project:
    workers: 1
    syncPeriod: 5m
  workspace:
    workers: 1
    syncPeriod: 5m
