dockerRegistryMirror: "https://jacob.pub/docker.io/"

metrics:
  serviceMonitor:
    enable: true
  proxy:
    image:
      repository: jacob.pub/quay.io/brancz/kube-rbac-proxy
      tag: v0.21.2@sha256:23bf4d4ddbb6827ede3a26d98814e3f3733b257e8b70de54c77e78eb7ed6d719

actionsMetrics:
  serviceMonitor:
    enable: true
  proxy:
    image:
      repository: jacob.pub/quay.io/brancz/kube-rbac-proxy
      tag: v0.21.2@sha256:23bf4d4ddbb6827ede3a26d98814e3f3733b257e8b70de54c77e78eb7ed6d719

image:
  repository: "jacob.pub/docker.io/summerwind/actions-runner-controller"
  actionsRunnerRepositoryAndTag: "jacob.pub/docker.io/summerwind/actions-runner:latest"
  dindSidecarRepositoryAndTag: "jacob.pub/docker.io/docker:dind"
