# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backup-rtz-uploads
  namespace: minio
spec:
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      backup-rtz-uploads:
        type: cronjob
        cronjob:
          schedule: 0 3 * * *
          concurrencyPolicy: Replace
          ttlSecondsAfterFinished: 3600
        containers:
          backup-rtz-uploads:
            image:
              repository: jacob.pub/docker.io/rclone/rclone
              tag: 1.73.3@sha256:66af24d7c8809af336dc16068149257cf447c80f8c60aa9f5679153f42017b85
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: minio-backup-credentials
                    key: accesskey
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: minio-backup-credentials
                    key: secretkey
              - name: RCLONE_CONFIG_B2_ACCOUNT
                valueFrom:
                  secretKeyRef:
                    name: b2-backup-credentials
                    key: account
              - name: RCLONE_CONFIG_B2_KEY
                valueFrom:
                  secretKeyRef:
                    name: b2-backup-credentials
                    key: key
            args:
              - --config
              - /rclone.conf
              - --stats=30s
              - --stats-one-line-date
              - sync
              - minio:rtz-uploads
              - b2:mcswain-minio/rtz-uploads
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi

    configMaps:
      config:
        data:
          rclone.conf: |
            [b2]
            type = b2
            hard_delete = true
            [minio]
            type = s3
            provider = Minio
            env_auth = true
            endpoint = https://s3.mcswain.dev

    persistence:
      config:
        enabled: true
        type: configMap
        name: backup-rtz-uploads
        advancedMounts:
          backup-rtz-uploads:
            backup-rtz-uploads:
              - path: /rclone.conf
                subPath: rclone.conf
