apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: disabled
resources:
  - ns.yaml
  - data.yaml
  - helm.yaml
  - networkpolicy.yaml
  - prom.yaml
  - backend-traffic-policy.yaml
  - securitypolicy.yaml
  - backup-astro.yaml
  - backup-rtz-uploads.yaml
  - backup-tandoor.yaml
configMapGenerator:
  - name: chart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
