apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: relax-sounds
  namespace: relax-sounds
spec:
  interval: 1h
  targetNamespace: relax-sounds
  path: ./apps/relax-sounds/resources/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: restic
  namespace: relax-sounds
spec:
  interval: 1h
  targetNamespace: relax-sounds
  path: ./apps/relax-sounds/resources/restic
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  commonMetadata:
    annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
