apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 1h
  targetNamespace: mosquitto
  path: ./services/mosquitto/resources/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: restic
  namespace: mosquitto
spec:
  interval: 1h
  targetNamespace: mosquitto
  path: ./services/mosquitto/resources/restic
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto-exporter
  namespace: mosquitto
spec:
  interval: 1h
  targetNamespace: mosquitto
  path: ./services/mosquitto/resources/exporter
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
