apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexrad-aws-notifier
  namespace: nexrad-aws-notifier
spec:
  install:
    remediation:
      retries: -1
  interval: 60m0s
  maxHistory: 2
  driftDetection:
    mode: enabled
  releaseName: nexrad-aws-notifier
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chart-values
