# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
controllers:
  filebrowser:
    replicas: 1
    containers:
      filebrowser:
        image:
          repository: jacob.pub/docker.io/filebrowser/filebrowser
          tag: v2.63.20
        args:
          - --database
          - /database/filebrowser.db
          - --address
          - 0.0.0.0
          - --noauth
        resources:
          limits: {}
          requests: {}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: path-of-titans

service:
  filebrowser:
    controller: filebrowser
    ports:
      http:
        port: 8080
        protocol: TCP

persistence:
  data:
    existingClaim: path-of-titans
    globalMounts:
    - path: /srv
  config:
    enabled: true
    type: configMap
    name: filebrowser
    globalMounts:
    - path: /config/settings.json
      subPath: settings.json
  database:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn-ssd

ingress:
  tailscale:
    enabled: true
    className: tailscale
    hosts:
      - host: filebrowser
        paths:
        - path: /
          pathType: Prefix
          service:
              identifier: filebrowser
              port: http
    tls:
      - hosts:
          - filebrowser

configMaps:
  config:
    data:
      settings.json: |
        {}
