---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: not-found
spec:
  directResponse:
    statusCode: 404
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: receiver-1090
spec:
  directResponse:
    statusCode: 200
    contentType: application/json
    body:
      type: Inline
      inline: '{"version":"v10.2","refresh":1000,"history":120}'
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: receiver-978
spec:
  directResponse:
    statusCode: 200
    contentType: application/json
    body:
      type: Inline
      inline: '{"version":"dump978 e827042","refresh":1000,"history":120}'
