apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 1h
  targetNamespace: cnpg-system
  path: ./infrastructure/cnpg/resources/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alerts
  namespace: cnpg-system
spec:
  interval: 1h
  targetNamespace: cnpg-system
  path: ./infrastructure/cnpg/resources/alerts
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backup-prune
  namespace: cnpg-system
spec:
  interval: 1h
  targetNamespace: cnpg-system
  path: ./infrastructure/cnpg/resources/backup-prune
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
