apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ses-email-service
  namespace: ses-email-service
spec:
  interval: 1h
  dependsOn:
    - name: reflector-creds
      namespace: reflector
    - name: cert-manager-certs
      namespace: cert-manager
  targetNamespace: ses-email-service
  path: ./infrastructure/ses-email-service/resources/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: ses-email-service
spec:
  interval: 1h
  targetNamespace: ses-email-service
  path: ./infrastructure/ses-email-service/resources/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
