apiVersion: v1
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:umkUv0NftEvcbRphFvZ/R7A9IEs=,iv:/O1SCUENNNs9E4sFW1Wo3WDJ9OPpO6JkuOVJrqJ8K7M=,tag:Dxj0Hhfe7KLlQJ/RpmRMsQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:4KmbeZgTV/WP9ZXBY+SqiSeF6Zabgv2vwnmQAQISo6Ag6FMMzm9Wxg==,iv:iCtW9wrKvJcCXuVkLH3EdBbbbObGtaRqvYEdZU82oD4=,tag:lC7Tn/H8IX7XM9kR69Skdg==,type:str]
    aws-smtp-password: ENC[AES256_GCM,data:AglHfhWs0hcSdB3TPQDtSN3GdKkRZtQ+xNJ+xfgCWG3pCjvP+o92zT6lSAQ=,iv:lPMSxuMZMBzZE05d/76ZHVblxMQri6vrgqaEu9tiXXc=,tag:pyCbz19h/9/GjPQBKYT7iA==,type:str]
    aws-smtp-username: ENC[AES256_GCM,data:BXFEA238pTx/7PtrFdkEx6RuvG4=,iv:fbrr1JyVWkzY4hdEGUW9Ik888ZwTmKVzERrpPvr5pFg=,tag:NtWjeGCbvxB7ZHaDRpMIvQ==,type:str]
kind: Secret
metadata:
    name: ses-email-service
    namespace: ses-email-service
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-10-09T21:15:47Z"
    mac: ENC[AES256_GCM,data:A2xZV8opbIpD2H5jqVce8P3IqOgbR262FIcWSU2Oz0/FHDYnk2QrphQs7yqQ6l63FS6m4kHPl5rOWvQwCMt30H9e4tjz6FNHb+PwdlBx1RHUCN5lTODYXNORhCiNBdD86BFdWRSGR2XuqnnAFvOFF/I/M6JN4EZbEpzAGtapwr4=,iv:L5resk+zm+i0BDUUA5Rnk1QmfZDty76c/Zymy4LXB7o=,tag:xyubnTkAhrFM5RioIiaW2A==,type:str]
    pgp:
        - created_at: "2026-10-09T21:15:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4MMKSOyI68lAQ/+MU56NXw0QQ5XznJM7AwRp57vUw0ntdi2uHJBJORjdAse
            m51lZsoBfHVANVxQOzgfNSR/DsTz9scN59+RGt8yWcIeKqSRO/ipnOoXQxLoIurN
            aws73kezExDOfNEW0EPeFn3gv/7Zms2zzxi3VyoiheQocoIyBgjAxB6E0koI4DNP
            NqNhCHPJGuHO2hLwiEr/3fCfASxu4yfyxfe8f/Kl4w+5A/7d4w778pOfru3Xhhjg
            khiOwPdRQm/2TJf/omgblWUwQj6i3Vr0/3/HirxUSOnebBi2njg9HMIEmPTpR/7Y
            HXsIdIMObc9NUs/Is8ty3UeOJx5cCkCxHmPS9PHZABrjvMFXen1tHASbbVbQqT25
            D68vk0Y2jT6x//+NgDIs9brxdT4zaOh3xZNazCz7ihWEn1hIUykIGYZIqs86TSQL
            vSNDC8lDGsVsVaeutWQxMvFHxb3vNlveyn6PHMu/iJAHTJnbzuVThJjMnqdeSMC2
            SYSYtjvohy3EEVzyDb7F+TgvGu+tZ5PBNkRFNIZmAYjK0JlADUhYECRRSAvLDbfs
            c7O4geORLNHTHykcbld+nFNBg0bi3w2viQ6geuu/b5HB27oJ0WHmDHw/bO86YJAS
            fza8aB59IeJlSn4+8+Y9GMC5fm5KkF0T3e4ah/ulEJ8MEM3pfvGUyioweIwzuUrS
            XgEIyrYfAu5dP+w1X9D7cp8KOq7yF25+y/jQ49DE5THtyi59M87mYVRWk6BXI+Fo
            dFeszW73LV6K9w5h+mJg3Yxb+yjEYHKwLcn2/rmVgnBF/Y1+bRrkFRJosXJYWDk=
            =KZAP
            -----END PGP MESSAGE-----
          fp: A2BDE47C6914DA528CE96C6042D82D6196E0B4FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
