# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  tfc-agent:
    replicas: 1
    containers:
      tfc-agent:
        image:
          repository: hashicorp/tfc-agent
          tag: 1.30.0@sha256:555085f130fdab7c452204457030ce533a249a87dd73d80ee4d0a3bbc88ab82b
          pullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
        env:
          TFC_ADDRESS: "https://tfe.mcswain.dev"
          TFC_AGENT_TOKEN:
            valueFrom:
              secretKeyRef:
                name: tfc-agent
                key: token
          TFC_AGENT_NAME: "tfc-agent"
          TFC_AGENT_OTLP_ADDRESS: "dynatrace-otel-collector.dynatrace-otel-collector.svc.cluster.local:4317"
