apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: usa-reddragon
        namespace: flux-system
      version: '1.1.2'
      interval: 60m0s
  interval: 1h
  values:
    controllers:
      valkey:
        containers:
          valkey:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.1.2-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11

    persistence:
      data:
        storageClass: longhorn-nvme
        accessMode: ReadWriteOnce
        size: 4Gi
        retain: true
