apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: usa-reddragon
        namespace: flux-system
      version: '1.1.2'
      interval: 60m0s
  interval: 1h
  values:
    controllers:
      valkey:
        containers:
          valkey:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 8.1.10-alpine@sha256:081c2f5cb575efc901aa80ff9cdbd1ec6a301682fd35e1ebb4b0990a4a4a8507

    persistence:
      data:
        storageClass: longhorn-nvme
        accessMode: ReadWriteOnce
        size: 4Gi
        retain: true
