---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ses-email-service-reconciler
  namespace: ses-email-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ses-email-service-reconciler
  namespace: ses-email-service
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ses-email-service-reconciler
  namespace: ses-email-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ses-email-service-reconciler
subjects:
- kind: ServiceAccount
  name: ses-email-service-reconciler
  namespace: ses-email-service
