---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ses-email-service
  namespace: ses-email-service
spec:
  interval: 60m0s
  url: https://github.com/USA-RedDragon/ses-email-service
  ref:
    branch: main
