# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  golink:
    forceRename: golink-app
    strategy: Recreate
    pod:
      enableServiceLinks: true
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    containers:
      app:
        image:
          repository: jacob.pub/ghcr.io/tailscale/golink
          tag: 1.0.0@sha256:e629f13cf8dcf9224e26317630172b3dcf1e69a44e5902207a38d4fe9e69bb3a
          pullPolicy: IfNotPresent
        args:
        - -sqlitedb
        - /data/golink.db
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale
              key: authkey
        - name: XDG_CONFIG_HOME
          value: /data
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
service:
  app:
    forceRename: golink-app
    controller: golink
    ports:
      http:
        port: 8080
persistence:
  data:
    type: persistentVolumeClaim
    forceRename: data
    retain: true
    storageClass: longhorn-ssd
    accessMode: ReadWriteOnce
    size: 2Gi
    advancedMounts:
      golink:
        app:
        - path: /data
          subPath: data
