# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  apprise:
    replicas: 1
    containers:
      apprise:
        image:
          repository: jacob.pub/lscr.io/linuxserver/apprise-api
          tag: 1.5.1@sha256:643684be0914b28a10a9eb759bb2474bf97a3e7ec725cf7f029f05770553ebfd
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
        resources:
          limits:
            memory: 120Mi
          requests:
            cpu: 10m
            memory: 80Mi

service:
  apprise:
    controller: apprise
    ports:
      http:
        port: 8000

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn-ssd

ingress:
  tailscale:
    enabled: true
    className: tailscale
    hosts:
      - host: apprise
        paths:
        - path: /
          pathType: Prefix
          service:
              identifier: apprise
              port: http
    tls:
      - hosts:
          - apprise
