apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
  namespace: smartctl-exporter
spec:
  interval: 1h
  install:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  releaseName: smartctl-exporter
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: chart-values
