# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  smartctl-exporter:
    type: daemonset
    pod:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
    containers:
      app:
        image:
          repository: jacob.pub/quay.io/prometheuscommunity/smartctl-exporter
          tag: v0.15.0@sha256:a76e08dbf5db4781fefd1ed81c65ad46ae8d2849dae6b6d3acebcde2fc4e59d6
        args:
          - --smartctl.interval=120s
          - --smartctl.rescan=10m
          - --web.listen-address=:9633
          - --smartctl.device-include=^(nvme[0-9]+|sd[ab])$
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /metrics
                port: 9633
              periodSeconds: 60
              timeoutSeconds: 30
          readiness:
            enabled: false
          startup:
            enabled: false
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
service:
  app:
    controller: smartctl-exporter
    ports:
      metrics:
        port: 9633
serviceMonitor:
  app:
    serviceName: smartctl-exporter
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        interval: 2m
        scrapeTimeout: 60s
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            targetLabel: node
persistence:
  dev:
    type: hostPath
    hostPath: /dev
    globalMounts:
      - path: /dev
