controllers:
  mariadb:
    containers:
      mariadb:
        image:
          repository: jacob.pub/ghcr.io/mariadb/mariadb
          tag: 12.3.3-noble@sha256:8da72d6ab7f1edffd540486662663b163c83a2c4755a6611e880010f41fe761f
        env:
          MARIADB_DATABASE: weewx
          MARIADB_USER: weewx
        resources:
          requests:
            memory: 256Mi
            cpu: 30m
          limits: {}

persistence:
  data:
    storageClass: longhorn-nvme
    accessMode: ReadWriteOnce
    size: 8Gi
