controllers:
  mariadb:
    containers:
      mariadb:
        image:
          repository: jacob.pub/ghcr.io/mariadb/mariadb
          tag: 12.3.2-noble@sha256:ef26b7cead9791369fa06c4879ffe0cc8b19518502fff3ad56d3058866ca4192
        env:
          MARIADB_DATABASE: weewx
          MARIADB_USER: weewx
        resources:
          requests:
            memory: 256Mi
            cpu: 30m
          limits: {}

persistence:
  data:
    storageClass: longhorn-nvme
    accessMode: ReadWriteOnce
    size: 8Gi
