controllers:
  mariadb:
    containers:
      mariadb:
        image:
          repository: jacob.pub/ghcr.io/mariadb/mariadb
          tag: 12.3.3-noble@sha256:4283f970a08e8aff32e37449be0810812f2cb0467d77866e996621306fe4246e
        env:
          MARIADB_DATABASE: weewx
          MARIADB_USER: weewx
        resources:
          requests:
            memory: 256Mi
            cpu: 30m
          limits: {}

persistence:
  data:
    storageClass: longhorn-nvme
    accessMode: ReadWriteOnce
    size: 8Gi
