# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

controllers:
  zot:
    strategy: RollingUpdate
    replicas: 1
    pod:
      priorityClassName: system-cluster-critical
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      labels:
        valkey-client: "true"
    initContainers:
      render:
        image:
          repository: ghcr.io/valkey-io/valkey
          tag: 8.1.10-alpine@sha256:b21fd94099dcd4bc6b2b9230daef69b6558b887ad4a2a1afe56ff6e745a88cdb
          pullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -ec
          - |
            umask 077
            awk '{ while ((i = index($0, "__VALKEY_PASSWORD__")) > 0) $0 = substr($0, 1, i - 1) ENVIRON["VALKEY_PASSWORD"] substr($0, i + 19); print }' /etc/zot/template/config.yaml > /etc/zot/rendered/config.yaml
            printf '{"clientid":"%s","clientsecret":"%s"}' "$OIDC_CLIENT_ID" "$OIDC_CLIENT_SECRET" > /etc/zot/rendered/oidc.json
        env:
          - name: VALKEY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: valkey-password
                key: valkey_password
          - name: OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: zot-oidc
                key: zot_oidc_clientid
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: zot-oidc
                key: zot_oidc_clientsecret
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
    containers:
      zot:
        args:
        - serve
        - /etc/zot/rendered/config.yaml
        image:
          repository: ghcr.io/project-zot/zot
          tag: v2.1.22@sha256:96cda11459ce6f8c60da3b03f03e9f67fd11b3ae2d82c4c04c92b3c608996080
          pullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              periodSeconds: 10
              failureThreshold: 720
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio
                key: accesskey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: secretkey

service:
  zot:
    controller: zot
    ports:
      http:
        port: 5000

configMaps:
  config:
    data:
      config.yaml: |
        http:
          address: 0.0.0.0
          port: 5000
          externalUrl: https://jacob.pub
          compat: [docker2s2]
          accessControl:
            adminPolicy:
              groups: [trusted]
              actions: [create, read, update, delete, detectManifestCollision]
            repositories:
              "**":
                defaultPolicy: [read]
              "pub/**":
                defaultPolicy: [read]
                anonymousPolicy: [read]
            metrics:
              anonymousPolicy: [read]
          auth:
            failDelay: 3
            sessionKeysFile: /etc/zot/sessionkeys.json
            openid:
              providers:
                oidc:
                  issuer: https://authentik.mcswain.dev/application/o/zot/
                  scopes: [openid, profile, email, groups]
                  credentialsFile: /etc/zot/rendered/oidc.json
        log:
          level: info
        extensions:
          ui:
            enable: true
          search:
            enable: true
          metrics:
            enable: true
            prometheus:
              path: /metrics
          sync:
            enable: true
            credentialsFile: /etc/zot/registry-credentials/credentials.json
            DownloadDir: /zot
            registries:
              - urls:
                  - https://ghcr.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/ghcr.io"
              - urls:
                  - https://docker.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/docker.io"
              - urls:
                  - https://git.scottlabs.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/git.scottlabs.io"
              - urls:
                  - https://quay.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/quay.io"
              - urls:
                  - https://lscr.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/lscr.io"
              - urls:
                  - https://nvcr.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/nvcr.io"
              - urls:
                  - https://reg.kyverno.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/reg.kyverno.io"
              - urls:
                  - https://registry.k8s.io
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/registry.k8s.io"
              - urls:
                  - https://docker.gitea.com
                onDemand: true
                maxRetries: 5
                retryDelay: 5m
                onlySigned: false
                content:
                  - prefix: "**"
                    stripPrefix: false
                    destination: "/docker.gitea.com"

        storage:
          rootDirectory: /zot
          remoteCache: true
          fastRestart: true
          cacheDriver:
            name: redis
            addr: [valkey:6379]
            password: "__VALKEY_PASSWORD__"
          dedupe: false
          storageDriver:
            name: s3
            regionendpoint: minio.minio.svc.cluster.local:9000
            forcepathstyle: true
            region: us-east-1
            bucket: zot
            secure: false

persistence:
  config:
    enabled: true
    type: configMap
    name: zot
    advancedMounts:
      zot:
        render:
          - path: /etc/zot/template
            readOnly: true
  rendered:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Mi
    advancedMounts:
      zot:
        render:
          - path: /etc/zot/rendered
        zot:
          - path: /etc/zot/rendered
            readOnly: true
  registry-credentials:
    enabled: true
    type: secret
    name: zot-registry-credentials
    advancedMounts:
      zot:
        zot:
          - path: /etc/zot/registry-credentials/credentials.json
            subPath: credentials.json
  sessionkeys:
    enabled: true
    type: secret
    name: zot-sessionkeys
    advancedMounts:
      zot:
        zot:
          - path: /etc/zot/sessionkeys.json
            subPath: sessionkeys
  auth-cert:
    enabled: true
    type: secret
    name: zot-auth-cert
    advancedMounts:
      zot:
        zot:
          - path: /ssl/tls.crt
            subPath: tls.crt
  zot:
    enabled: true
    type: emptyDir
    sizeLimit: 10Gi
    advancedMounts:
      zot:
        zot:
          - path: /zot

serviceMonitor:
  zot:
    enabled: true
    serviceName: zot
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 30s

route:
  zot:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - jacob.pub
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /metrics
        filters:
          - type: ExtensionRef
            extensionRef:
              group: gateway.envoyproxy.io
              kind: HTTPRouteFilter
              name: not-found
      - backendRefs:
          - name: zot
            port: 5000
        matches:
          - path:
              type: PathPrefix
              value: /
        timeouts:
          request: 0s
          backendRequest: 0s
  registry:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: public
        namespace: envoy-gateway-system
        sectionName: https
    hostnames:
      - jacob.pub
    rules:
      - backendRefs:
          - name: zot
            port: 5000
        matches:
          - path:
              type: PathPrefix
              value: /v2
        timeouts:
          request: 0s
          backendRequest: 0s
