apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm.yaml
  - metrics-actioner-helm.yaml
  - metrics-actioner-metrics.yaml
  - metrics-actioner-rbac.yaml
  - log-alerts.yaml
  - talos-logs.yaml
  - alloy-gateway-svc.yaml
  - loki-alert-rules.yaml
  - router-scrape.yaml
  - backup-alerts.yaml
  - modem-exporter
  - observatory-svc.yaml
  - thanos-prom.yaml
configMapGenerator:
  - name: querier-chart-values
    files:
      - values.yaml=querier-values.yaml
  - name: compactor-chart-values
    files:
      - values.yaml=compactor-values.yaml
  - name: store-chart-values
    files:
      - values.yaml=store-values.yaml
  - name: pushgateway-chart-values
    files:
      - values.yaml=pushgateway-values.yaml
  - name: metrics-actioner-chart-values
    files:
      - values.yaml=metrics-actioner-values.yaml
  - name: loki-chart-values
    files:
      - values.yaml=loki-values.yaml
  - name: alloy-chart-values
    files:
      - values.yaml=alloy-values.yaml
  - name: alloy-gateway-chart-values
    files:
      - values.yaml=alloy-gateway-values.yaml
configurations:
  - kustomizeconfig.yaml
