fullnameOverride: snmp-exporter

image:
  repository: jacob.pub/quay.io/prometheus/snmp-exporter

resources:
  requests:
    cpu: 10m
    memory: 48Mi
  limits:
    memory: 128Mi

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

serviceMonitor:
  enabled: false
